### ISSUE TITLE
Garbage collected trace objects (`dyn Trace`)

### ISSUE THREAD

**Issue by andersk** [DuckLogic/zerogc#15]
The current `Trace` trait is not object-safe, so it can’t be used with trait objects:

```rust
trait Foo: Trace {
    fn foo(&self);
}

#[derive(Trace)]
struct AnyFoo(dyn Foo);
```

Could it be made object-safe by turning the associated constants into functions and moving the `V: GcVisitor` type parameter of `Trace::visit<V>` up to `Trace<V>::visit`?

**Comment by Techcable** [comment]
Oh man :frowning_face:  Based on my experiments today, this is hard to do right.

I **really** don't want to parameterize `Trace` like `Trace<V: GcVisitor>`. 

I've played around with having a separate set of `DynTrace` and `DynGcVisitor` taits (kind of like [erased-serde](https://docs.rs/erased-serde/0.3.13/erased_serde/)) but its hard to write blanket impls over regular `Trace`/`GcVisitor` traits because they expect statically visible type info.

I'm starting to think maybe I should go closer to the approach you suggested and modify `Trace` and `GcVisitor` to be object safe directly.
I really want to keep support for `NEEDS_TRACE`, but that is hard to do since associated constants aren't supported on trait objects :frowning: There is no way to add a special `where Self: Sized` bound. Maybe I can move it to a separate trait and then specialize?

Kind of just throwing out random suggestions here. This project is still a little experimental :smile: :wink: 

This is related to #16 because both arrays and trait objects are `?Sized`.

**Comment by Techcable** [comment]
The new [Pointee](https://doc.rust-lang.org/nightly/std/ptr/trait.Pointee.html) type and the nightly `ptr_metadata` API may significantly change this. (See rust-lang/rust#81513)

I'm hesitant to refactor the API design to depend so heavily on a nightly feature, however that may be the only way I can reasonably implement this feature.

In practice, however, `zerogc` is already limited to nightly because the `simple` collector requires nightly (although this is mostly for convenience at this point).
